/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as EquipmentRouteImport } from './routes/equipment'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MemberIdRouteImport } from './routes/member.$id'

const EquipmentRoute = EquipmentRouteImport.update({
  id: '/equipment',
  path: '/equipment',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MemberIdRoute = MemberIdRouteImport.update({
  id: '/member/$id',
  path: '/member/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/equipment': typeof EquipmentRoute
  '/member/$id': typeof MemberIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/equipment': typeof EquipmentRoute
  '/member/$id': typeof MemberIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/equipment': typeof EquipmentRoute
  '/member/$id': typeof MemberIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/equipment' | '/member/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/equipment' | '/member/$id'
  id: '__root__' | '/' | '/equipment' | '/member/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EquipmentRoute: typeof EquipmentRoute
  MemberIdRoute: typeof MemberIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/equipment': {
      id: '/equipment'
      path: '/equipment'
      fullPath: '/equipment'
      preLoaderRoute: typeof EquipmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/member/$id': {
      id: '/member/$id'
      path: '/member/$id'
      fullPath: '/member/$id'
      preLoaderRoute: typeof MemberIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EquipmentRoute: EquipmentRoute,
  MemberIdRoute: MemberIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
