/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PProjectIdRouteImport } from './routes/p.$projectId'
import { Route as PProjectIdIndexRouteImport } from './routes/p.$projectId.index'
import { Route as PProjectIdSettingsRouteImport } from './routes/p.$projectId.settings'
import { Route as PProjectIdEquipmentRouteImport } from './routes/p.$projectId.equipment'
import { Route as PProjectIdMemberIdRouteImport } from './routes/p.$projectId.member.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PProjectIdRoute = PProjectIdRouteImport.update({
  id: '/p/$projectId',
  path: '/p/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const PProjectIdIndexRoute = PProjectIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PProjectIdRoute,
} as any)
const PProjectIdSettingsRoute = PProjectIdSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => PProjectIdRoute,
} as any)
const PProjectIdEquipmentRoute = PProjectIdEquipmentRouteImport.update({
  id: '/equipment',
  path: '/equipment',
  getParentRoute: () => PProjectIdRoute,
} as any)
const PProjectIdMemberIdRoute = PProjectIdMemberIdRouteImport.update({
  id: '/member/$id',
  path: '/member/$id',
  getParentRoute: () => PProjectIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/p/$projectId': typeof PProjectIdRouteWithChildren
  '/p/$projectId/equipment': typeof PProjectIdEquipmentRoute
  '/p/$projectId/settings': typeof PProjectIdSettingsRoute
  '/p/$projectId/': typeof PProjectIdIndexRoute
  '/p/$projectId/member/$id': typeof PProjectIdMemberIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/p/$projectId/equipment': typeof PProjectIdEquipmentRoute
  '/p/$projectId/settings': typeof PProjectIdSettingsRoute
  '/p/$projectId': typeof PProjectIdIndexRoute
  '/p/$projectId/member/$id': typeof PProjectIdMemberIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/p/$projectId': typeof PProjectIdRouteWithChildren
  '/p/$projectId/equipment': typeof PProjectIdEquipmentRoute
  '/p/$projectId/settings': typeof PProjectIdSettingsRoute
  '/p/$projectId/': typeof PProjectIdIndexRoute
  '/p/$projectId/member/$id': typeof PProjectIdMemberIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/p/$projectId'
    | '/p/$projectId/equipment'
    | '/p/$projectId/settings'
    | '/p/$projectId/'
    | '/p/$projectId/member/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/p/$projectId/equipment'
    | '/p/$projectId/settings'
    | '/p/$projectId'
    | '/p/$projectId/member/$id'
  id:
    | '__root__'
    | '/'
    | '/p/$projectId'
    | '/p/$projectId/equipment'
    | '/p/$projectId/settings'
    | '/p/$projectId/'
    | '/p/$projectId/member/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PProjectIdRoute: typeof PProjectIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$projectId': {
      id: '/p/$projectId'
      path: '/p/$projectId'
      fullPath: '/p/$projectId'
      preLoaderRoute: typeof PProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$projectId/': {
      id: '/p/$projectId/'
      path: '/'
      fullPath: '/p/$projectId/'
      preLoaderRoute: typeof PProjectIdIndexRouteImport
      parentRoute: typeof PProjectIdRoute
    }
    '/p/$projectId/settings': {
      id: '/p/$projectId/settings'
      path: '/settings'
      fullPath: '/p/$projectId/settings'
      preLoaderRoute: typeof PProjectIdSettingsRouteImport
      parentRoute: typeof PProjectIdRoute
    }
    '/p/$projectId/equipment': {
      id: '/p/$projectId/equipment'
      path: '/equipment'
      fullPath: '/p/$projectId/equipment'
      preLoaderRoute: typeof PProjectIdEquipmentRouteImport
      parentRoute: typeof PProjectIdRoute
    }
    '/p/$projectId/member/$id': {
      id: '/p/$projectId/member/$id'
      path: '/member/$id'
      fullPath: '/p/$projectId/member/$id'
      preLoaderRoute: typeof PProjectIdMemberIdRouteImport
      parentRoute: typeof PProjectIdRoute
    }
  }
}

interface PProjectIdRouteChildren {
  PProjectIdEquipmentRoute: typeof PProjectIdEquipmentRoute
  PProjectIdSettingsRoute: typeof PProjectIdSettingsRoute
  PProjectIdIndexRoute: typeof PProjectIdIndexRoute
  PProjectIdMemberIdRoute: typeof PProjectIdMemberIdRoute
}

const PProjectIdRouteChildren: PProjectIdRouteChildren = {
  PProjectIdEquipmentRoute: PProjectIdEquipmentRoute,
  PProjectIdSettingsRoute: PProjectIdSettingsRoute,
  PProjectIdIndexRoute: PProjectIdIndexRoute,
  PProjectIdMemberIdRoute: PProjectIdMemberIdRoute,
}

const PProjectIdRouteWithChildren = PProjectIdRoute._addFileChildren(
  PProjectIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PProjectIdRoute: PProjectIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
